### PR TITLE
Testing

### LINKED ISSUE #40: php-xml, php-mbstring dependencies missing
After a fresh Yunohost + Baikal installation, I could not open e.g. Baikal/dav.php because of a DOMDocument error. After installing php-xml and php-mbstring by hand the pages started to work.

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *well-known urls are unique per domain*

- *No change_url script*

- *Global upgrade of the package.*

- *php-xml, php-mbstring dependencies missing #40*

## Solution
- *Check if well-known urls are available before installing and restoring the app.*  
- *Fix https://github.com/YunoHost-Apps/baikal_ynh/issues/17 and https://github.com/YunoHost-Apps/baikal_ynh/issues/25*
- *Add a change_url script*
- *Update to baikal 0.5.3*
- *Install [dependencies](https://github.com/sabre-io/Baikal/wiki/Ba%C3%AFkal-dependencies) Fix #40*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : Kay0u
- [x] **Approval (LGTM)** : Kay0u
- [ ] **Approval (LGTM)** : 
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/baikal_ynh%20PR37/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by kay0u** [comment]
Should we wait for #39?

**Comment by kay0u** [comment]
Bump :-)

**Comment by JimboJoe** [comment]
Can be merged in 3 days (if the CI says so).

**Comment by kay0u** [comment]
CI said yes!!! 🎉

**Pull request merged**
