### PR TITLE
Update to 0.5.3

### PR DESCRIPTION
**Pull request by optikfluffel**
## Problem
- There's a newer baikal version (0.5.3) out there. (#38)

## Solution
- Use it.

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : Maniack C
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/baikal_ynh%20PR39/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
LGTM
Don't know about the patches. JimboJoe, could you check it ?

**Comment by maniackcrudelis** [comment]
The CI has moved to https://ci-apps-hq.yunohost.org, that wasn't a mistake ;)

**Comment by optikfluffel** [comment]
@maniackcrudelis I'm sorry, I was still trying to fix the badge. I just leave it alone xD

**Comment by maniackcrudelis** [comment]
To not have too much call to github, the CI will check this repo in a hour.
You can expect the badge in 1 hour or 2.
But that's right, that's not that obvious ;)

**Comment by optikfluffel** [comment]
@maniackcrudelis also: why don't you make `testing` your default branch here, when you want devs to add to this one? I didn't realize there was one before you mentioning it (yes, I _should_ have read the README all to the end, I know xD).

**Comment by maniackcrudelis** [comment]
Historically because we had many user installing apps directly from their repo, so from the default branch.
No that we moved to a list for all apps. Well... I guess we could think about that.
Many dev forget to work on testing when making their PR. Not only you, don't worry.

**Comment by JimboJoe** [comment]
The patches look good to me (and no error at patch time), but I haven't tested.

**Comment by JimboJoe** [comment]
Can be merged in 3 days.

**Pull request merged**
