### PR TITLE
Upgrade to 0.6.0

### LINKED ISSUE #43: Update to Baikal 6
Baikal 6 is now out so this app should be updated soon.

https://github.com/sabre-io/Baikal/releases/tag/0.6.0

### PR DESCRIPTION
**Pull request by kay0u**
## Solution
- *Upgrade to 0.6.1, Fix #43*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : frju365
- [x] **Approval (LGTM)** : frju365
- [x] **Approval (LGTM)** : JimboJoe
- **CI succeeded** : 
[Build Status](https://ci-apps-hq.yunohost.org/jenkins/job/baikal_ynh%20PR44/)  
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by JimboJoe** [comment]
Can be merged in 3 days.

**Comment by Gofannon** [comment]
In the [baikal upgrade documentation](http://sabre.io/baikal/upgrade/), it is written

> Upload the contents of the zip file to the server, but make sure **you do not overwrite the Specific directory. Everything else may be overwritten.** Keep the whole Specific directory intact. Baïkal needs all files, not just the database.

Does the upgrade script handles this? (I didn't test)

-------

Also, `version 6.1` has been released: https://github.com/sabre-io/Baikal/blob/master/CHANGELOG.md

**Comment by kay0u** [comment]
> In the [baikal upgrade documentation](http://sabre.io/baikal/upgrade/), it is written
> 
> > Upload the contents of the zip file to the server, but make sure **you do not overwrite the Specific directory. Everything else may be overwritten.** Keep the whole Specific directory intact. Baïkal needs all files, not just the database.
> 
> Does the upgrade script handles this? (I didn't test)
> 
> Also, `version 6.1` has been released: https://github.com/sabre-io/Baikal/blob/master/CHANGELOG.md

Thank you, it should be fixed now!

**Comment by JimboJoe** [comment]
Can be merged in 3 days.

**Pull request merged**
