### PR TITLE
Fix install + refactoring

### PR DESCRIPTION
**Pull request by JimboJoe**
## Problem
- *Install broken*
- *Need a whole refactoring*

## Solution
- *Package refactored to adjust to latest standards*

## PR Status
Work finished. Package_check, basic tests and upgrade from last version OK.  
Could be reviewed and tested.  

## Validation
~*Medium decision*~
- [ ] ~**Complete test** :~
- [ ] ~**Upgrade previous version** :~
- [X] ~**Code review** : JimboJoe~
- [ ] ~**Code review** :~
- [X] ~**Approval (LGTM)** : JimboJoe~
- [ ] ~**Approval (LGTM)** :~
- [ ] ~**Approval (LGTM)** :~
- [X] ~**CI succeeded** : JimboJoe~
- [ ] ~**CI succeeded** :~
~One public package check log is enough instead of two checks.  
When the PR is mark as ready to merge, you have to wait for 7 days before really merge it.~

Since this PR has been rerouted from master to testing. It passes to a minor decision.
- [X] **Upgrade previous version** : JimboJoe
- [x] **Code review** : JimboJoe
- [x] **Approval (LGTM)** : JimboJoe
- [x] **Approval (LGTM)** : frju365 
- [x] **CI succeeded** : JimboJoe
When the PR is mark as ready to merge, you have to wait for 3 days before really merge it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
Linked to https://github.com/YunoHost-Apps/baikal_ynh/pull/20, so I should not review this PR by myself.

**Comment by JimboJoe** [comment]
Yes, I had to re-create the PR as my commit wasn't showing up... 😦 
I've reviewed it, but now I can't approve it (from the GitHub point of view) 😀

**Comment by JimboJoe** [comment]
Upgrade from previous version failed: at least the `config.system.php` file is not correctly filled (due to the use of `db_name` setting in upgrade, and that setting didn't exist in previous version).

**Comment by JimboJoe** [comment]
OK, upgrade from last version works fine now 👍 
We just need a small LGTM (and someone that actually approve the PR) and we can merge to testing.

**Comment by maniackcrudelis** [comment]
@YunoHost-Apps/apps-group Please, just one small LGTM...

**Comment by Rafi594** [comment]
This new version works fine on my test VM

**Comment by frju365** [comment]
ok. Can be merged in 3 days !

**Pull request merged**
